name: appcenter_bundle
description: This plugin currently bundles AppCenter Analytics, Crashes and Distribute. To learn more about AppCenter, go to https://aka.ms/appcenterdocs
version: 1.0.1
homepage: https://github.com/cavecafe/appcenter_bundle

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: any
  test: any

flutter:
  plugin:
    platforms:
      android:
        package: com.github.cavecafe.appcenter_bundle
        pluginClass: AppcenterBundlePlugin
      ios:
        pluginClass: AppcenterBundlePlugin
