name: appcenter_bundle
description: >-
This plugin bundles AppCenter Analytics, Crashes and Distribute, 
from the original 'flutter_appcenter_bundle', added fixes of the following

    1. Update to avoid null safety check compiler errors in later version of dart compilers
    2. Update to Kotlin Plugin version to the later version of 2022 and later

To learn more about AppCenter, go to https://aka.ms/appcenterdocs
version: 1.0.3
homepage: https://github.com/cavecafe/appcenter_bundle
issue_tracker: https://github.com/cavecafe/appcenter_bundle/issues
publish_to: https://pub.dev
repository: https://github.com/cavecafe/appcenter_bundle.git
environment:
  sdk: ">=2.12.0 <3.22.1"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: any
  test: any

flutter:
  plugin:
    platforms:
      android:
        package: com.github.cavecafe.appcenter_bundle
        pluginClass: AppcenterBundlePlugin
      ios:
        pluginClass: AppcenterBundlePlugin
